# Site settings
author: Lenny Lee
title: My Blog
header-img: img/home-bg.png
email: lennylee91@gmail.com
copyright_name: Lenny Lee
description: > # this means to ignore newlines until "baseurl:"
  General code info
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  KingLeotheCat

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
